### ISSUE TITLE
feat: fallback RPCs

### ISSUE THREAD

**Issue by thomas779** [useloopso/BMR#4]
**Problem**
The current implementation does not consider fallback RPCs in the event the RPC is unresponsive due to downtime. 

**Solution**
The best solution is to run a node in-house & have a fallback, but we are cheapskates so we should have fallbacks.

**Tasks**
- [x] If the response is too slow, abort and use fallback RPC.
- [x] If tx fails, try with a different RPC.

**Requirements**
- Must have at least 1 fallback per connected chain.
- May require DB connector to track events (storing in memory may be sufficient).

**Comment by lajosdeme** [comment]
implemented in #7
