### ISSUE TITLE
feat: append `wl` character as prefix to token symbols

### ISSUE THREAD

**Issue by thomas779** [useloopso/BMR#5]
**Problem**
Right now, we are the only bridge on the market, but as many more pop up, the user will need to know which token is native vs. custodied by a bridge.

**Solution**
The solution is to add a letter `wl` in front of token symbols to distinguish between other bridges. This is useful because devs and users will know _who_ is in custody of that symbol and improves UX on readability.

**Example**
A user bridges `USDT` from chain A to chain B. The relayer should pick up the symbol and mint the token `wlUSDT` on chain B.

Note: `wlUSDT` = `wrapped loopso USDT`

**Comment by lajosdeme** [comment]
implemented in #6
